### ISSUE TITLE
Just Brilliant

### ISSUE THREAD

**Issue by PythonLinks** [davidesantangelo/dato.rss#1]
Hats off to whoever created this.  You get my highest compliments.  It changed my thinking. 

There is a huge problem with the MSM blackout of progressive news.  It is not like Tienamen Square in China, where there are literally no mentions of the massacre.  The web pages are there, just the MSM algorithms do not show us the pages.   How do we circumvent the the media blackout.  Well with RSS.  

I have quite a few RSS feeds and a custom build feed reader, I curate and republish the news, but this is really the missing piece. 

Okay, so where do I find your list of RSS feeds?  

I run https://GreenMaps.US.  I have quite a large stack or RSS feeds. 

I am not quite sure how I will interact with this project., but I am certainly going to be thinking about it.

**Comment by davidesantangelo** [comment]
Hi thank you very much

at the moment only I can add rss feed to the import. Can you shoot me the URLs so I can add them.

There is yet the API to do this (https://github.com/davidesantangelo/dato.rss/wiki/Feed)  in the future I will unlock it.

Keep an eye on the project.

**Comment by PythonLinks** [comment]
I signed up to watch this project.  I recently started using Ruby, and prefer it to python, particularly for multiple processors.  But Since my servers are in Python, on the ZODB, I will use the Whoosh search library to index my RSS feeds.  
How sad.
