### ISSUE TITLE
mention the wiki

### ISSUE THREAD

**Issue by PythonLinks** [davidesantangelo/dato.rss#4]
I am increasingly interested in this project.  
I returned to learn more, but found an empty README. 
You may want to mention that there is more documentation in the wiki, give people a pointer where to look.  Or at least have a paragraph or two of introduction. 

When I last looked at it, there was a huge software stack.  Kind of scared me off.  

Next question, I am practicing Software archeology.  Trying to figure out how this thing is bult. A paragraph or two on architecture with some links to where the code is would be most helpful.  I do not have rails experience, so I am not quie sure where to look.  Eventullly I will figure it out thought.

**Comment by PythonLinks** [comment]
I see.  All of that stuff is there, under the image.  The image is so large, that I thought nothing was under it.  My mistake.  My apologies.

**Comment by davidesantangelo** [comment]
don't worry :)
